datagrid:
    app-issues-grid:
        extended_entity_name: AppBundle:Issue
        options:
            entity_pagination: true
        source:
            acl_resource: app_issue_view
            type: orm
            query:
                select:
                    - distinct issue.id
                    - issue.code
                    - issue.summary
                    - typeEnum.name as issueType
                    - priorityEnum.name as issuePriority
                    - resolutionEnum.name as issueResolution
                    - reporter.username as reporterUsername
                    - assignee.username as assigneeUsername
                    - issue.createdAt
                    - issue.updatedAt
                from:
                    - { table: AppBundle:Issue, alias: issue }
                join:
                    left:
                        - { join: issue.priority, alias: priorityEnum }
                        - { join: issue.type, alias: typeEnum }
                        - { join: issue.resolution, alias: resolutionEnum }
                        - { join: issue.assignee, alias: assignee }
                        - { join: issue.reporter, alias: reporter }
                        - { join: issue.collaborators, alias: collaborator }
        columns:
            code:
                label: Code
            summary:
                label: Summary
            issueType:
                label: Type
            issuePriority:
                label: Priority
            issueResolution:
                label: Resolution
            reporterUsername:
                label: Reporter
            assigneeUsername:
                label: Assignee
            createdAt:
                label: Created
                frontend_type: datetime
            updatedAt:
                label: Updated
                frontend_type: datetime
        properties:
            id: ~
            view_link:
                type: url
                route: app_issue_view
                params:
                    - id
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
                acl_resource:  app_issue_view
                rowAction:     true
        sorters:
            columns:
                code:
                    data_name: issue.code
                summary:
                    data_name: issue.summary
                issueType:
                    data_name: issueType
                issuePriority:
                    data_name: issuePriority
                issueResolution:
                    data_name: issueResolution
                reporterUsername:
                    data_name: reporterUsername
                assigneeUsername:
                    data_name: assigneeUsername
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
            default:
                updatedAt: DESC
        filters:
            columns:
                code:
                    type: string
                    data_name: issue.code
                summary:
                    type: string
                    data_name: issue.summary
                issuePriority:
                    type: enum
                    data_name: issuePriority
                    enum_code: issue_priority
                issueType:
                    type: enum
                    data_name: issueType
                    enum_code: issue_type
                issueResolution:
                    type: enum
                    data_name: issueResolution
                    enum_code: issue_resolution
                assignee:
                    type: entity
                    data_name: assignee
                    label: Assignee
                    options:
                        field_type:     entity
                        field_options:
                            class: Oro\Bundle\UserBundle\Entity\User
                reporter:
                    type: entity
                    data_name: reporter
                    label: Reporter
                    options:
                        field_type:     entity
                        field_options:
                            class: Oro\Bundle\UserBundle\Entity\User
                collaborator:
                    type: entity
                    data_name: collaborator
                    label: Collaborator
                    options:
                        field_type:     entity
                        field_options:
                            class: Oro\Bundle\UserBundle\Entity\User
                createdAt:
                    type: datetime
                    data_name: issue.createdAt
                updatedAt:
                    type: datetime
                    data_name: issue.updatedAt
    app-issue-collaborators-grid:
        source:
            acl_resource: oro_user_view
            type: orm
            query:
                select:
                    - user.id
                    - user.username
                    - user.firstName
                    - user.lastName
                from:
                    - { table: AppBundle:Issue, alias: issue }
                join:
                    left:
                        - { join: issue.collaborators, alias: user }

                where:
                    and:
                        - issue.id = :issueId
            bind_parameters:
                - issueId
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [999]
                    default_per_page: 999
        columns:
            username:
                label: Username
            firstName:
                label: First Name
            lastName:
                label: Last Name
        properties:
            id: ~
            view_link:
                type: url
                route: oro_user_view
                params:
                    - id
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
                acl_resource:  oro_user_view
                rowAction:     true
    app-issue-subtasks-grid:
        extends: app-issues-grid
        source:
            query:
                join:
                    left:
                        - { join: issue.parent, alias: parent }
                where:
                    and:
                        - parent.id = :issueId
            bind_parameters:
                - issueId
        sorters: ~
        filters: ~
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [999]
                    default_per_page: 999
    app-assignee-issues-grid:
        extends: app-issues-grid
        source:
            query:
                join:
                    left:
                        - { join: issue.assignee, alias: user }
                where:
                    and:
                        - user.id = :userId
            bind_parameters:
                - userId
        sorters: ~
        filters: ~
    app-reporter-issues-grid:
        extends: app-issues-grid
        source:
            query:
                join:
                    left:
                        - { join: issue.reporter, alias: user }
                where:
                    and:
                        - user.id = :userId
            bind_parameters:
                - userId
        sorters: ~
        filters: ~
    app-users-active-issues-grid:
        extends: app-issues-grid
        source:
            query:
                join:
                    left:
                        - { join: issue.collaborators, alias: user }
                where:
                    and:
                        - user.id = :userId
                        - issue.resolution is null
            bind_parameters:
                - userId
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10
        sorters: ~
        filters: ~