datagrid:
    app-issues-grid:
        extended_entity_name: AppBundle:Issue
        options:
            entity_pagination: true
        source:
            acl_resource: app_issue_view
            type: orm
            query:
                select:
                    - distinct issue.id
                    - issue.code
                    - issue.summary
                    - typeEnum.name as issueType
                    - priorityEnum.name as issuePriority
                    - resolutionEnum.name as issueResolution
                    - reporter.username as reporterUsername
                    - assignee.username as assigneeUsername
                    - issue.createdAt
                    - issue.updatedAt
                from:
                    - { table: AppBundle:Issue, alias: issue }
                join:
                    left:
                        - { join: issue.priority, alias: priorityEnum }
                        - { join: issue.type, alias: typeEnum }
                        - { join: issue.resolution, alias: resolutionEnum }
                        - { join: issue.assignee, alias: assignee }
                        - { join: issue.reporter, alias: reporter }
                        - { join: issue.collaborators, alias: collaborator }
        columns:
            code:
                label: app.issue.code.label
            summary:
                label: app.issue.summary.label
            reporterUsername:
                label: app.issue.reporter.label
            assigneeUsername:
                label: app.issue.assignee.label
            createdAt:
                label: app.issue.created.label
                frontend_type: datetime
            updatedAt:
                label: app.issue.updated.label
                frontend_type: datetime
        properties:
            id: ~
            view_link:
                type: url
                route: app_issue_view
                params:
                    - id
            update_link:
                type: url
                route: app_issue_update
                params:
                    - id
            delete_link:
                type: url
                route: app_api_delete_issue
                params:
                    - id
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
                acl_resource:  app_issue_view
                rowAction:     true
            update:
                type:           navigate
                label:          Update
                link:           update_link
                icon:           edit
                acl_resource:   app_issue_update
            delete:
                type:           delete
                label:          Delete
                link:           delete_link
                icon:           trash
                acl_resource:   app_issue_delete
        sorters:
            columns:
                code:
                    data_name: issue.code
                summary:
                    data_name: issue.summary
                reporterUsername:
                    data_name: reporterUsername
                assigneeUsername:
                    data_name: assigneeUsername
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
            default:
                updatedAt: DESC
        filters:
            columns:
                code:
                    type: string
                    data_name: issue.code
                summary:
                    type: string
                    data_name: issue.summary
                issuePriority:
                    label: 'app.issue.priority.label'
                    type: enum
                    data_name: issuePriority
                    enum_code: issue_priority
                issueType:
                    label: 'app.issue.type.label'
                    type: enum
                    data_name: issueType
                    enum_code: issue_type
                issueResolution:
                    label: 'app.issue.resolution.label'
                    type: enum
                    data_name: issueResolution
                    enum_code: issue_resolution
                assigneeUsername:
                    type: entity
                    data_name: assignee
                    options:
                        field_type:     entity
                        field_options:
                            class: Oro\Bundle\UserBundle\Entity\User
                reporterUsername:
                    type: entity
                    data_name: reporter
                    label: Reporter
                    options:
                        field_type:     entity
                        field_options:
                            class: Oro\Bundle\UserBundle\Entity\User
                collaborator:
                    label: 'app.issue.collaborators.label'
                    type: entity
                    data_name: collaborator
                    options:
                        field_type:     entity
                        field_options:
                            class: Oro\Bundle\UserBundle\Entity\User
                createdAt:
                    type: datetime
                    data_name: issue.createdAt
                updatedAt:
                    type: datetime
                    data_name: issue.updatedAt
    app-issue-collaborators-grid:
        source:
            acl_resource: oro_user_view
            type: orm
            query:
                select:
                    - user.id
                    - user.username
                    - user.firstName
                    - user.lastName
                from:
                    - { table: AppBundle:Issue, alias: issue }
                join:
                    left:
                        - { join: issue.collaborators, alias: user }

                where:
                    and:
                        - issue.id = :issueId
            bind_parameters:
                - issueId
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [999]
                    default_per_page: 999
        columns:
            username:   ~
            firstName:  ~
            lastName:   ~
        properties:
            id: ~
            view_link:
                type: url
                route: oro_user_view
                params:
                    - id
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
                acl_resource:  oro_user_view
                rowAction:     true
    app-issue-subtasks-grid:
        extends: app-issues-grid
        source:
            query:
                join:
                    left:
                        - { join: issue.parent, alias: parent }
                where:
                    and:
                        - parent.id = :issueId
            bind_parameters:
                - issueId
        sorters: ~
        filters: ~
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [999]
                    default_per_page: 999
    app-assignee-issues-grid:
        extends: app-issues-grid
        source:
            query:
                join:
                    left:
                        - { join: issue.assignee, alias: user }
                where:
                    and:
                        - user.id = :userId
            bind_parameters:
                - userId
        sorters: ~
        filters: ~
    app-reporter-issues-grid:
        extends: app-issues-grid
        source:
            query:
                join:
                    left:
                        - { join: issue.reporter, alias: user }
                where:
                    and:
                        - user.id = :userId
            bind_parameters:
                - userId
        sorters: ~
        filters: ~
    app-users-active-issues-grid:
        extends: app-issues-grid
        source:
            query:
                join:
                    left:
                        - { join: issue.collaborators, alias: user }
                where:
                    and:
                        - user.id = :userId
            bind_parameters:
                - userId
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10
        sorters: ~
        filters:
            default:
                workflowStepLableByWorkflowStep:
                    value:
                        a: 2