AppBundle\Entity\Issue:
    alias:          app_issue
    title_fields:   [summary]
    search_template: AppBundle:Issue:searchResult.html.twig
    route:
        name: app_issue_view
        parameters:
            id: id
    fields:
        -
            name: summary
            target_type: text
        -
            name: code
            target_type: text
        -
            name: priority
            relation_type: many-to-one
            relation_fields:
                -
                    name: name
                    target_type: text
                    target_fields: [name]
        -
            name: type
            relation_type:          many-to-one
            relation_fields:
                -
                    name:                   name
                    target_type:            text
                    target_fields:          [name]
        -
            name: resolution
            relation_type:          many-to-one
            relation_fields:
                -
                    name:                   name
                    target_type:            text
                    target_fields:          [name]
        -
            name: assignee
            relation_type:          many-to-one
            relation_fields:
                -
                    name:                   username
                    target_type:            text
                    target_fields:          [all_data]
        -
            name: reporter
            relation_type:          many-to-one
            relation_fields:
                -
                    name:                   username
                    target_type:            text
                    target_fields:          [all_data]