services:
    app.issue_manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - AppBundle\Entity\Issue
            - "@doctrine.orm.entity_manager"
    app.issue_listener:
        class: AppBundle\EventListener\IssueListener
        arguments:
            - '@oro_workflow.manager'
        tags:
            - { name: doctrine.orm.entity_listener }